[package]
name = "batt-mon"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
codegen-units = 1

[dependencies]
notify-rust = {version="4.11.0", default-features=false, features=["zbus", "serde"]}
snafu = "0.8.2"
